// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Product.Data;

#nullable disable

namespace Product.Migrations
{
  // [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Product.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This Is Product One",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This Is Product Two",
                            Name = "DeskTop"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This Is Product Three",
                            Name = "Printer"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This Is Product Four",
                            Name = "HeadPhone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
